package handlers

import (
	"encoding/json"
	"net/http"

	"MFBasketBacktester/internal/backtest"
	"MFBasketBacktester/internal/cache"
	"MFBasketBacktester/internal/claude"
	"MFBasketBacktester/internal/db"
	"MFBasketBacktester/internal/models"
)

// summaryResponse pairs the numeric backtest result with its AI summary.
type summaryResponse struct {
	Basket  string                `json:"basket"`
	Result  models.BacktestResult `json:"result"`
	Summary string                `json:"summary"`
}

// GetSummary handles POST /summary — it runs a backtest and returns a
// plain-language summary of the result generated by Claude.
func (h *Handlers) GetSummary(w http.ResponseWriter, r *http.Request) {
	var req models.BacktestRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		writeError(w, http.StatusBadRequest, "invalid JSON body")
		return
	}
	if req.BasketID <= 0 {
		writeError(w, http.StatusBadRequest, "valid basket_id is required")
		return
	}

	basket, err := db.GetBasket(req.BasketID)
	if err != nil {
		writeError(w, http.StatusNotFound, "basket not found")
		return
	}

	key := cacheKey(req)
	var result models.BacktestResult
	if cached, err := cache.GetBacktestResult(key); err == nil && cached != nil {
		result = *cached
	} else {
		result, err = backtest.Run(req.BasketID, req.StartDate, req.EndDate, req.Amount)
		if err != nil {
			writeError(w, http.StatusBadRequest, err.Error())
			return
		}
		_ = cache.SetBacktestResult(key, result)
	}

	summary, err := claude.Summarize(r.Context(), h.ClaudeAPIKey, basket.Name, result)
	if err != nil {
		writeError(w, http.StatusBadGateway, "could not generate summary: "+err.Error())
		return
	}

	writeJSON(w, http.StatusOK, summaryResponse{
		Basket:  basket.Name,
		Result:  result,
		Summary: summary,
	})
}
